// Static fallback data shown until real DB rows exist.
// Once enough activity has been generated by the founder, these constants
// stop being read (queries return DB rows instead).

// Static activity series for the dashboard line chart.
// Replace with a real per-week aggregation once enough call history exists.
export const callSeries = {
  labels: ["W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8"],
  callsMade: [12, 14, 18, 17, 22, 25, 28, 26],
  pickedUp: [6, 7, 9, 8, 11, 13, 15, 14],
  conversations: [3, 4, 5, 5, 7, 8, 10, 9],
};

// Coaching-panel fallback. Used only until the on-demand grader (triggered
// from the dashboard) has written real rows. Tuned for the four objection
// categories the founder hears most often: content, budget, venue, time.
export const scoreBreakdown = [
  { label: "Content scope clarity", score: 68 },
  { label: "Budget probe timing", score: 56 },
  { label: "Venue + delivery commit", score: 52 },
  { label: "Time-block negotiation", score: 61 },
  { label: "3-question discovery hit rate", score: 74 },
];

export const opportunities = [
  {
    title: "Content scope answered too generically",
    impact: { text: "high impact", tone: "bad" as const },
    detail:
      "Buyers ask what's covered; \"AI workflows / prompt engineering / agentic dev\" reads as filler. Tie each module to the answer they gave on AI-knowledge level.",
  },
  {
    title: "Budget probe asked too late in the call",
    impact: { text: "high impact", tone: "bad" as const },
    detail:
      "Leaving the budget question until the last 5 minutes means you scope a 30-pax cohort the buyer can't fund this quarter. Probe budget after headcount, before content.",
  },
  {
    title: "Venue + delivery date left vague in proposal",
    impact: { text: "medium", tone: "warn" as const },
    detail:
      "\"Sometime in Q3\" pushes the deal to next quarter. Quote on-site vs remote with two specific date options on the first proposal.",
  },
];

export const wins: [string, string, string][] = [
  ["3-question discovery completion", "84%", "of calls"],
  ["Headcount → cohort mapping accepted", "+22%", "close rate"],
  ["On-site quote anchored at proposal", "61%", "of wins"],
  ["Date locked within 7 days of proposal", "3.4d", "median"],
];
